### ISSUE TITLE
Cygwin child process exited ABNORMALLY(0)

### ISSUE THREAD

**Issue by kingcc** [shunf4/proxychains-windows#10]
Hello,

An error occurred when I tried below command in this environment:

```sh
$ proxychains curl google.com
> [I] 2020/09/22 13:53:35 posix_spawnp ret: 0; CYGPID: 4061
    [I] 2020/09/22 13:53:35 Cygwin child process pid 4061 exited ABNORMALLY(0).
```

Environment:
- Windows Terminal 1.2.2381.0 With Zsh
- Proxychains.exe Cygwin 64-bit Release 0.6.8
- curl 7.55.1 (Windows) libcurl/7.55.1 WinSSL

**Comment by shunf4** [comment]
Please retry using Mintty or Conhost rather than Windows Terminal and post the results here.

Also, it's not recommended to use Proxychains.exe Cygwin with executable that is not built for Cygwin. Try Proxychains.exe Win32 for this curl version, or Proxychains.exe Cygwin for /bin/curl that is built for cygwin.

**Comment by kingcc** [comment]
I got it. Thanks
