### ISSUE TITLE
proxychains_win32_x64d.exe - what does the d mean?

### ISSUE THREAD

**Issue by bs27975** [shunf4/proxychains-windows#27]
Until this project, I have never come across the ...x64d.exe and ...x86d.exe filename forms. Without the d before the extension, yes, but not with the d.

[Yes, it is clear that the file(s) can be renamed, but that is not the question.]

What does the 'd' stand for, and could an article in the wiki be added to so explain, please?

**Comment by shunf4** [comment]
Obviously suffix "d" stands for "debug", for it appears only in debug release zips. So I don't feel the need to write it in Wiki or elsewhere.

Actually adding suffix "d" to static and dynamic libraries is a Microsoft convention: https://docs.microsoft.com/en-us/cpp/porting/visual-cpp-change-history-2003-2015?view=msvc-160#general-changes

**Comment by shunf4** [comment]
Yeah you reminded me. I should have released the .pdb files along with the debug binaries.

**Comment by bs27975** [comment]
> Obviously suffix "d" stands for "debug", for it appears only in debug binary zips. So I don't feel the need to write it in Wiki or elsewhere.

No, it is not at all in any way obvious.

I had no idea I was in a debug version of anything.

Given that, a short note in the wiki would seem, at the least, a minimal courtesy.

> Actually adding suffix "d" to static and dynamic libraries is a Microsoft convention: https://docs.microsoft.com/en-us/cpp/porting/visual-cpp-change-history-2003-2015?view=msvc-160#general-changes

Thanks. I had no idea of that.

Let alone, I do not view proxychains as a library. (So that point doesn't apply here.)

**Comment by shunf4** [comment]
> I had no idea I was in a debug version of anything.

Why? I thought one will understand what "d" means upon unzipping the archive, and finding the binaries suffixed by "d" compared to those in Release archive.

Did you go straight towards the debug binaries at the beginning?

> So that point doesn't apply here

Yes it does apply, at least for curl: https://github.com/curl/curl/issues/1286

And by a quick analogy, one will understand "d" in proxychainsd.exe when they know what "d" in proxychainsd.dll means.

**Comment by shunf4** [comment]
On a second thought I admit this suffix may be misinterpreted as something like server or "deamon".

I think I won't change the filenames, though; for now I will add something descriptive in release description.

**Comment by bs27975** [comment]
> > I had no idea I was in a debug version of anything.
> 
> Why? I thought one will understand what "d" means upon unzipping the archive, and finding the binaries suffixed by "d" compared to those in Release archive.
> 
> Did you go straight towards the debug binaries at the beginning?
> 
> > So that point doesn't apply here
> 
> Yes it does apply, at least for curl: [curl/curl#1286](https://github.com/curl/curl/issues/1286)
> 
> And by a quick analogy, one will understand "d" in proxychainsd.exe when they know what "d" in proxychainsd.dll means.

<<<<<
Build
First you need to clone this repository and run git submodule update --init --recursive in it to retrieve all submodules.

Win32 Build
Open proxychains.exe.sln with a recent version Visual Studio (tested with Visual Studio 2019) with platform toolset v141_xp on a 64-bit Windows.

Build the whole solution and you will see DLL file and executable file generated under win32_output/.
>>>>>
<<<<<
git clone https://github.com/shunf4/proxychains-windows.git
>>>>>

There is no zipping. There is no debug, there is no release.

- git clone
- build
- copy .exe's.
- full stop, per instructions.

**Comment by shunf4** [comment]
You are talking about building it from source. That's another thing.

There is only brief instructions for building and developing, providing only necessary information for a successful build (no matter whether there is the suffix). No "d" meaning, no how to configure x64/x86 and Release/Debug to get various outputs, no meaning of variable names like `cbRead` ([Hungarian Notation](https://docs.microsoft.com/en-us/windows/win32/learnwin32/windows-coding-conventions#hungarian-notation)), no why I use `push rbp; sub rsp, 1024; lea rbp, [rsp+512];` in hook function, etc.

For the unexplained parts, I expect you to explore them as a developer (or at least a power user) with enough Win32 dev experience. Above all, the .sln file, the .vcxproj files and the source code are there for you to check it out.

I had the same experience when I came across things like "freeglutd.lib" and "python_d.exe", and also "libxxx.a" in UNIX world. I got answers from Q&A sites, instead of from official docs.

There is not enough time for maintainers to teach people to properly use compilation flags, resolve dependency issues, fix compatibility problems, etc, much less to explain a thing of convention. This is for sure much less than prefect, but it is the status quo.

So feel free to edit the project Wiki, adding anything which you think is important.

**Comment by shunf4** [comment]
Or should I make it clear in README that one can easily download the pre-built binaries from [Release Page](https://github.com/shunf4/proxychains-windows/releases), just as with most F/LOSS software on GitHub?

**Comment by bs27975** [comment]
YES! Please!

I had no idea there was a releases page. I came across the effort, read the front page that said I must build the win binaries myself, then started jumping through the hoops and hurdles of doing so. With the resulting comments you have seen.

**Comment by bs27975** [comment]
> So feel free to edit the project Wiki, adding anything which you think is important.

Thanks for letting me know that. I did not expect you would want people randomly scribbling in your wiki, so I held off.

**Comment by shunf4** [comment]
I've updated the README.

Well, GitHub is more of a place to build software than to ship the software. But even there's not an obvious "download" button that redirects to the release page, we still assumed everyone checked the release page first, and that was a mistake.
