### ISSUE TITLE
DNS resolving

### ISSUE THREAD

**Issue by autogun** [shunf4/proxychains-windows#5]
Can't seems to make DNS resolving work.

Trying to use `proxychains-windows` to run [mRemoteNG](https://mremoteng.org/) which currently does not support proxying RDP traffic (https://github.com/mRemoteNG/mRemoteNG/issues/420).

While connecting to an IP address works perfectly, using DNS (which can only be resolved on proxy server, and on the PC running `mRemoteNG`) doesn't work.

Attached DEBUG verbose output (with a little obscuration)
[proxychains_debug.log](https://github.com/shunf4/proxychains-windows/files/4544637/proxychains_debug.log)

**Comment by shunf4** [comment]
Providing `DEBUG` level log should be enough.

Cannot reproduce. Used proxychains on mRemoteNG, and proxified RDP connection works normally.

![Pic1](https://user-images.githubusercontent.com/20991618/80480593-8860fc80-8983-11ea-9559-01ad34784901.png)

![Pic2](https://user-images.githubusercontent.com/20991618/80480662-a4fd3480-8983-11ea-8b55-633b2118607f.png)

I have noticed "goto out as-is" in the log. This ususally means either a `GetAddrInfoW` (name resolution) call's parameters or its return value(like, empty - your hostname cannot be resolved locally) is not suitable for proxychains to intercept. The conditions are below:

https://github.com/shunf4/proxychains-windows/blob/4f0a1bea670a9dc451389ebf6f9de4f05c1c6b12/src/dll/hook_connect_win32.c#L1467-L1486

Please provide further information, like:
- your configuration
- whether the hostname resolves on your PC *locally* (rather than on your proxy server)

**Comment by autogun** [comment]
1. My config is mostly default. I only commented out `IP-CIDR` as I need the traffic proxied to those networks. [[proxychains.conf.txt](https://github.com/shunf4/proxychains-windows/files/4545822/proxychains.conf.txt)]
2. The hostname is _not_ resolved locally. It is only resolved on the proxy server.

It's important to mention as I'm on VPN, connected to my corp network. Without being connected to the VPN, I cannot use the proxy server, therefore I cannot test it at all.

**Comment by shunf4** [comment]
> 2\. The hostname is _not_ resolved locally

Then it satisfies condition `pOriginalResultCast == NULL`, which causes hooked `GetAddrInfoW` to return a null resolved address list.

I will consider a proper fix in the future. For the time being you can try one of these three workarounds:

- set `force_resolve_by_hosts_file` to 0 in configuration, add your hostname to system `hosts` file with an arbitrary IP address and retry.
- make your hostname resolvable by adjusting your LAN DNS settings
- lift the restriction by commenting out this line and recompile:
https://github.com/shunf4/proxychains-windows/blob/4f0a1bea670a9dc451389ebf6f9de4f05c1c6b12/src/dll/hook_connect_win32.c#L1482

**Comment by autogun** [comment]
@shunf4 Thanks for looking into that.

System `hosts` file works of course. Even without setting `force_resolve_by_hosts_file` to `0`. What does it actually do?

Just want to point out that forwarding DNS requests is pretty common, FireFox proxy settings has an option for that -
![image](https://user-images.githubusercontent.com/11921235/80501954-bbea5980-8978-11ea-9f8f-b652ef0923c9.png)

**Comment by shunf4** [comment]
@autogun When `force_resolve_by_hosts_file` is set to 1, all hostnames that exist in `hosts` file are resolved locally, no matter whether they match the routing rules. In this case we want the proxy server to resolve the hostname for us (because we might not know what it is resolved to), so we set `force_resolve_by_hosts_file` to 0 and assign a arbitrary address to the hostname in `hosts`. You must have given it a correct IP address in `hosts`, so even without changing `force_resolve_by_hosts_file` things should work.

DNS request forwarding _does_ exist in current version(by requesting the SOCKS5 proxy server to connect to a hostname instead of an IP address), but every name is locally resolved before further routing decision. This is incorrect. It causes DNS leak and cases like this issue could happen. I will redesign the logic of this part in the future, if I have time.

**Comment by autogun** [comment]
> set `force_resolve_by_hosts_file` to `0` and assign a arbitrary address to the hostname in hosts.

This works only when default `hosts` file is used (C:\Windows\System32\drivers\etc\hosts).
Once I tried setting `custom_hosts_file_path` and using the same arbitrary address for that hostname, I get `goto out as-is`.

Debug shows it picked up my custom hosts file -
`[D] 2020/04/29 12:49:55 HostsFilePath: C:\Users\autogun\.proxychains\custom_hosts`

**Comment by shunf4** [comment]
Proxychains cannot control which `hosts` is used in local resolution. Custom hosts file is only used in routing decision, after local resolution.

**Comment by autogun** [comment]
Alright, no more complaints from my side 😉
Thanks for the great effort!

**Comment by shunf4** [comment]
Tried to fix it and published a pre-release 0.6.6: https://github.com/shunf4/proxychains-windows/releases/tag/0.6.6

**Comment by autogun** [comment]
@shunf4 at first glance and by simply replacing IPs to FQDNs in mRemoteNG it works. Thank you!

**Comment by shunf4** [comment]
FYI [the flow chart of name resolution](https://github.com/shunf4/proxychains-windows/blob/master/doc/name_resolution.md).
